name: Build PKHeX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'   # Ensure you're using .NET 8.0

      - name: Install dependencies
        run: dotnet restore

      - name: Build PKHeX
        run: dotnet build --configuration Release

      - name: Test PKHeX (optional, if there are tests)
        run: dotnet test --configuration Release
